services:
  - type: web
    name: ccproxy
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.render
    dockerCommand: ccproxy serve --host 0.0.0.0 --port $PORT --sdk-enable-pool
    healthCheckPath: /health
    autoDeploy: true
