services:
  - type: web
    name: ccproxy-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: ccproxy --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: SERVER__HOST
        value: 0.0.0.0
      # Render tek tıkta bir gizli anahtar üretsin:
      - key: SECURITY__AUTH_TOKEN
        generateValue: true
