services:
  - type: web
    name: ccproxy
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.render
    # Start Command'覺 da burada net veriyoruz ki eski --port/--host kal覺nt覺lar覺 override edilsin
    dockerCommand: sh -lc "SERVER__HOST=0.0.0.0 SERVER__PORT=$PORT ccproxy --sdk-enable-pool"
    healthCheckPath: /health
    autoDeploy: true
